### ISSUE TITLE
Property 'name' does not exist on type 'IGuessReturn'

### ISSUE THREAD

**Issue by homebrewhops** [Ionaru/MarketBot#1]
Running in to this issue when I run sudo npm start. Running sudo npm install results in 'up to date'
```
sudo npm start

> MarketBot@1.1.0 start /var/marketbot/MarketBot
> npm run build && node dist/index.js


> MarketBot@1.1.0 build /var/marketbot/MarketBot
> tsc --project tsconfig.json

**src/helpers/guessers.spec.ts(41,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.
src/helpers/guessers.spec.ts(48,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.
src/helpers/guessers.spec.ts(55,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.
src/helpers/guessers.spec.ts(62,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.
src/helpers/guessers.spec.ts(84,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.
src/helpers/guessers.spec.ts(115,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.
src/helpers/guessers.spec.ts(122,27): error TS2339: Property 'name' does not exist on type 'IGuessReturn'.**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! MarketBot@1.1.0 build: `tsc --project tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the MarketBot@1.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marketbot/.npm/_logs/2017-09-18T19_02_37_692Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! MarketBot@1.1.0 start: `npm run build && node dist/index.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the MarketBot@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marketbot/.npm/_logs/2017-09-18T19_02_37_714Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle MarketBot@1.1.0~prestart: MarketBot@1.1.0
6 info lifecycle MarketBot@1.1.0~start: MarketBot@1.1.0
7 verbose lifecycle MarketBot@1.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle MarketBot@1.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/marketbot/MarketBot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle MarketBot@1.1.0~start: CWD: /var/marketbot/MarketBot
10 silly lifecycle MarketBot@1.1.0~start: Args: [ '-c', 'npm run build && node dist/index.js' ]
11 silly lifecycle MarketBot@1.1.0~start: Returned: code: 2  signal: null
12 info lifecycle MarketBot@1.1.0~start: Failed to exec start script
13 verbose stack Error: MarketBot@1.1.0 start: `npm run build && node dist/index.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid MarketBot@1.1.0
15 verbose cwd /var/marketbot/MarketBot
16 verbose Linux 4.8.0-22-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error MarketBot@1.1.0 start: `npm run build && node dist/index.js`
22 error Exit status 2
23 error Failed at the MarketBot@1.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by Ionaru** [comment]
I didn't update the tests for the new guess function returns yet, that is what is causing the error.

But the real bug is that test files are compiled when trying to start the application.

I'll have a fix for all this very soon.
